### ISSUE TITLE
Add SPI support

### ISSUE THREAD

**Issue by alifeee** [ConnectedHumber/Bus-Terminal-Signs#4]
This is something I was working on (see [branch on the fork](https://github.com/alifeee/Bus-Terminal-Signs/tree/add-SPI)) but didn't get to finish. I will remain work on it soon. I place this issue here to remember to do so.

It speeds up the communication by 10 or 50 times, using Arduino's SPI library, as the clock pulse width can be as low as 10 ns (bit banging is 1 us).

**Comment by BNNorman** [comment]
Great improvements, thank you.

I planned to switch to SPI when I first created this repo but never got around to it.

**Comment by BNNorman** [comment]
We (connected humber) are meeting at the Makerspace tomorrow from 5:30 tomorrow. It would be good to shake hands.

**Comment by alifeee** [comment]
> We (connected humber) are meeting at the Makerspace tomorrow from 5:30 tomorrow. It would be good to shake hands.

I will be there :)
